### ISSUE TITLE
关于训练参数

### ISSUE THREAD

**Issue by xingcheng1061** [TY424/AbsGS#10]
作者您好，我下载了您的代码，并在mip-nerf360数据集上进行了实验，但是发现PSNR值跟论文中的水平差了1个多点，请问是训练参数设置的原因吗？我的训练代码如下：python train.py -s ../../dataset/360_extra_scenes/flowers/ -m ./output/flowers -r 4  --eval
![image](https://github.com/user-attachments/assets/03596a0a-bc04-4c20-9235-4e3acd5cd038)
![00000](https://github.com/user-attachments/assets/1be83102-e8a2-4896-bbb9-c9c4ffd86ac8)

**Comment by TY424** [comment]
> 作者您好，我下载了您的代码，并在mip-nerf360数据集上进行了实验，但是发现PSNR值跟论文中的水平差了1个多点，请问是训练参数设置的原因吗？我的训练代码如下：python train.py -s ../../dataset/360_extra_scenes/flowers/ -m ./output/flowers -r 4 --eval ![image](https://private-user-images.githubusercontent.com/149296024/379722419-03596a0a-bc04-4c20-9235-4e3acd5cd038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODQ2NzIsIm5iZiI6MTcyOTc4NDM3MiwicGF0aCI6Ii8xNDkyOTYwMjQvMzc5NzIyNDE5LTAzNTk2YTBhLWJjMDQtNGMyMC05MjM1LTRlM2FjZDVjZDAzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNTM5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2M1YjRjODZkZmY3ZTA4Zjk4MzY1YjEyY2VjNWIxNTVjMTA2NTlmZjc2NmMwNmQwNGU2NDc4MjRkYjNkZDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XLceLXn_yQZtLRl5_YilEZY2fJobUcMr--BbPJKc6V8) ![00000](https://private-user-images.githubusercontent.com/149296024/379722654-1be83102-e8a2-4896-bbb9-c9c4ffd86ac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODQ2NzIsIm5iZiI6MTcyOTc4NDM3MiwicGF0aCI6Ii8xNDkyOTYwMjQvMzc5NzIyNjU0LTFiZTgzMTAyLWU4YTItNDg5Ni1iYmI5LWM5YzRmZmQ4NmFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNTM5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTQ2MjgzOWM0OTc1ZTNjM2MwOTA3NDFlOWUzYWNmYmE0Mjc4Mjk5YTIzNjk0YTg1NTZhZGYyYzRhMDA2ZWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fS7VN_o-vAmoVUkrbiK5m4FQLhTkz3enh0LNZduFJPw)

要不试试 python train.py -s " + source + " -i images_4 -m " + args.output_path + "/" + scene + common_args。感觉这个结果好奇怪，比原本3DGS还低。点云是官方数据提供的吗？其他场景结果也是这样吗？

**Comment by xingcheng1061** [comment]
> > 作者您好，我下载了您的代码，并在mip-nerf360数据集上进行了实验，但是发现PSNR值跟论文中的水平差了1个多点，请问是训练参数设置的原因吗？我的训练代码如下：python train.py -s ../../dataset/360_extra_scenes/flowers/ -m ./output/flowers -r 4 --eval ![image](https://private-user-images.githubusercontent.com/149296024/379722419-03596a0a-bc04-4c20-9235-4e3acd5cd038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODQ2NzIsIm5iZiI6MTcyOTc4NDM3MiwicGF0aCI6Ii8xNDkyOTYwMjQvMzc5NzIyNDE5LTAzNTk2YTBhLWJjMDQtNGMyMC05MjM1LTRlM2FjZDVjZDAzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNTM5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2M1YjRjODZkZmY3ZTA4Zjk4MzY1YjEyY2VjNWIxNTVjMTA2NTlmZjc2NmMwNmQwNGU2NDc4MjRkYjNkZDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XLceLXn_yQZtLRl5_YilEZY2fJobUcMr--BbPJKc6V8) ![00000](https://private-user-images.githubusercontent.com/149296024/379722654-1be83102-e8a2-4896-bbb9-c9c4ffd86ac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODQ2NzIsIm5iZiI6MTcyOTc4NDM3MiwicGF0aCI6Ii8xNDkyOTYwMjQvMzc5NzIyNjU0LTFiZTgzMTAyLWU4YTItNDg5Ni1iYmI5LWM5YzRmZmQ4NmFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNTM5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTQ2MjgzOWM0OTc1ZTNjM2MwOTA3NDFlOWUzYWNmYmE0Mjc4Mjk5YTIzNjk0YTg1NTZhZGYyYzRhMDA2ZWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fS7VN_o-vAmoVUkrbiK5m4FQLhTkz3enh0LNZduFJPw)
> 
> 要不试试 python train.py -s " + source + " -i images_4 -m " + args.output_path + "/" + scene + common_args。感觉这个结果好奇怪，比原本3DGS还低。点云是官方数据提供的吗？其他场景结果也是这样吗？

点云数据是官方提供的，在3DGS和Mip-Splatting上都跑过没有问题，其它场景目前没有尝试。

**Comment by TY424** [comment]
@xingcheng1061 奇怪，可以对比一下3dgs和absgs这个场景每张图像的指标。

**Comment by xingcheng1061** [comment]
> @xingcheng1061 奇怪，可以对比一下3dgs和absgs这个场景每张图像的指标。

好的，我再多尝试一下

**Comment by xingcheng1061** [comment]
明白了，论文首页给的是单张图像的PSNR值，我算的是22张测试视角的平均值

**Comment by TY424** [comment]
> 明白了，论文首页给的是单张图像的PSNR值，我算的是22张测试视角的平均值

是的，主页中是单帧的数值。
