### ISSUE TITLE
为什么把float3* dL_dmean2D换成float4* dL_dmean2D

### ISSUE THREAD

**Issue by hjh530** [TY424/AbsGS#11]
感谢您和您团队的工作，这个地方我有些困惑，为什么把float3* dL_dmean2D改成float4* dL_dmean2D，当我在您的基础上修改这些代码时候出现了前向传播的维度与反向传播的维度不匹配的问题，原因是我按照下面的方式修改了这些维度代码[https://github.com/hwanhuh/diff-surfel-rasterization-MCMC/commit/4559add0b674d7045e4e7968bdd7689c80b23cdf](url)。所以仅仅修改反向传播中梯度计算的代码可以正常应用吗？

**Comment by TY424** [comment]
3DGS中float3* dL_dmean2D变量中仅使用了前两维（分别为x和y方向的梯度），改为float4* dL_dmean2D后，前两维不变，后两维为x和y方向的梯度AbsGrad。

**Comment by TY424** [comment]
@hjh530 
3DGS中float3* dL_dmean2D变量中仅使用了前两维（分别为x和y方向的梯度），改为float4* dL_dmean2D后，前两维不变，后两维为x和y方向的梯度AbsGrad。

“仅仅修改反向传播中梯度计算的代码可以正常应用吗？” 可以。
如果是在原版3DGS基础上可以这样简化操作，将float3* dL_dmean2D的前两维计算直接换成AbsGrad，这样的克隆和分裂将都采样绝对值梯度，也可已解决过度重建的模糊问题。

atomicAdd(&dL_dmean2D[global_id].x, dL_dG * dG_ddelx * ddelx_dx);
atomicAdd(&dL_dmean2D[global_id].y, dL_dG * dG_ddely * ddely_dy);
替换为：
atomicAdd(&dL_dmean2D[global_id].x, fabs(dL_dG * dG_ddelx * ddelx_dx));
atomicAdd(&dL_dmean2D[global_id].y, fabs(dL_dG * dG_ddely * ddely_dy));

最后说明一下，AbsGS的关键其实不仅在于具体的克隆与分裂策略，更重要的是提供了这样一种想法：高斯是否需要分裂应该与高斯对其覆盖像素的表达状态，即要考虑到每个像素，而不能仅考虑整体。因此，用颜色的梯度、分裂克隆都采用绝对值梯度等，其实都可以消除过度重建。

**Comment by hjh530** [comment]
感谢您百忙之中的回复，在看了论文之后我理解了您的想法，希望这个策略能够更好的重建出一些细节。

**Comment by TY424** [comment]
> @hjh530 3DGS中float3* dL_dmean2D变量中仅使用了前两维（分别为x和y方向的梯度），改为float4* dL_dmean2D后，前两维不变，后两维为x和y方向的梯度AbsGrad。
> 
> “仅仅修改反向传播中梯度计算的代码可以正常应用吗？” 可以。 如果是在原版3DGS基础上可以这样简化操作，将float3* dL_dmean2D的前两维计算直接换成AbsGrad，这样的克隆和分裂将都采样绝对值梯度，也可已解决过度重建的模糊问题。
> 
> atomicAdd(&dL_dmean2D[global_id].x, dL_dG * dG_ddelx * ddelx_dx); atomicAdd(&dL_dmean2D[global_id].y, dL_dG * dG_ddely * ddely_dy); 替换为： atomicAdd(&dL_dmean2D[global_id].x, fabs(dL_dG * dG_ddelx * ddelx_dx)); atomicAdd(&dL_dmean2D[global_id].y, fabs(dL_dG * dG_ddely * ddely_dy));
> 
> 最后说明一下，AbsGS的关键其实不仅在于具体的克隆与分裂策略，更重要的是提供了这样一种想法：高斯是否需要分裂应该与高斯对其覆盖像素的表达状态，即要考虑到每个像素，而不能仅考虑整体。因此，用颜色的梯度、分裂克隆都采用绝对值梯度等，其实都可以消除过度重建。

似乎不能直接这样做，dL_dmean2D会参与后续mean3D的计算，因此不能直接使用abs来替换。 @hjh530

**Comment by hjh530** [comment]
是的，这样做会导致显存异常增加，最终在几千次训练后出现cuda of memory，同时高斯点也增加异常。

**Comment by xiaoxiaozlx** [comment]
> 感谢您和您团队的工作，这个地方我有些困惑，为什么把float3* dL_dmean2D改成float4* dL_dmean2D，当我在您的基础上修改这些代码时候出现了前向传播的维度与反向传播的维度不匹配的问题，原因是我按照下面的方式修改了这些维度代码[https://github.com/hwanhuh/diff-surfel-rasterization-MCMC/commit/4559add0b674d7045e4e7968bdd7689c80b23cdf](url)。所以仅仅修改反向传播中梯度计算的代码可以正常应用吗？

您好，我按照这个连接中的修改也同样遇到了维度不匹配的问题，我想问下您是否解决这一问题？是如何解决的呢？因为我还有一些其他的修改，所以不能直接安装diff-gaussian-rasterization-abs，我尝试在我的方案中加入absGS中的思路，请问相对于原版3dgs，absGS都需要修改哪些内容呢？
