### ISSUE TITLE
How is this visualization achieved?

### ISSUE THREAD

**Issue by xuncpp** [TY424/AbsGS#13]
Hello! First of all, thank you for your excellent work.
I would like to ask how you achieve such visualization in your project page.
Thank you!
![1](https://github.com/user-attachments/assets/d31e1dad-e198-4c87-9594-40c32945f718)

**Comment by TY424** [comment]
Hello. You can achieve this visualization by selecting the Gaussian primitives and then modifying their 0th-order SH coefficients. @xuncpp

**Comment by xuncpp** [comment]
Thanks a lot!  I'll give it a try!
