### ISSUE TITLE
How to calculate Homodirectional Gradient

### ISSUE THREAD

**Issue by Dawn11041107** [TY424/AbsGS#2]
Hello, can I ask whether you use [codes from scene/gaussian_model.py](https://github.com/TY424/AbsGS/blob/main/scene/gaussian_model.py#L480-L482) to compute the "positional gradient" and the "absolute value of each component (x, y)" respectively? If yes, can you explain how it works?
The previous line(3D-GS) returns`[update_filter, :2]`, which means it's calculating the values in the x and y directions. But why does `[update_filter, 2:]`(AbsGS) return the elements starting from index 2, and those become the absolute values?

**Comment by TY424** [comment]
Hi, the gradient of mean2D is saved in [screenspace_points](https://github.com/TY424/AbsGS/blob/main/gaussian_renderer/__init__.py#L27) , and the gradient computation procedure is shown in code 
[backword.cu](https://github.com/TY424/AbsGS/blob/main/submodules/diff-gaussian-rasterization-abs/cuda_rasterizer/backward.cu#L544-L550).

**Comment by Dawn11041107** [comment]
> Hi, the gradient of mean2D is saved in [screenspace_points](https://github.com/TY424/AbsGS/blob/main/gaussian_renderer/__init__.py#L27) , and the gradient computation procedure is shown in code [backword.cu](https://github.com/TY424/AbsGS/blob/main/submodules/diff-gaussian-rasterization-abs/cuda_rasterizer/backward.cu#L544-L550).

Ah, I get it. Thank you SO much！（非常感谢你的回复^^！！
