### ISSUE TITLE
Problem about per-scene results in the paper 

### ISSUE THREAD

**Issue by sjj118** [TY424/AbsGS#3]
The last two rows of Table 8 seems to wrong. It's not compatible with the average LPIPS in Table 1 & 2.

<img width="1038" alt="Snipaste_2024-06-04_14-47-31" src="https://github.com/TY424/AbsGS/assets/5615018/92f4f373-c718-4f82-91a4-5d056dec6083">

**Comment by TY424** [comment]
Thank you for pointing out this mistake. We check with the original data and the correct data is as follows.
![2024-06-04_21-22](https://github.com/TY424/AbsGS/assets/45705137/02d1093e-081b-416d-a231-437939d45bbc)
