### ISSUE TITLE
How to plot the gradient?

### ISSUE THREAD

**Issue by Krisite** [TY424/AbsGS#4]
![Snipaste_2024-06-06_21-23-58](https://github.com/TY424/AbsGS/assets/43603799/c28ec9c4-a770-4784-8a6e-09361050f1d2)

**Comment by TY424** [comment]
Just add a variable to save the gradient of each pixel.

**Comment by charyang-ai** [comment]
> Just add a variable to save the gradient of each pixel.

add in where, cuda part or python part?
