### ISSUE TITLE
Floaters from overfit

### ISSUE THREAD

**Issue by Metro1998** [TY424/AbsGS#6]
Firstly, I want to express my sincere gratitude for open-sourcing such an outstanding project. While validating on my own dataset, I observed significant improvements in PSNR and SSIM, but inevitably encountered the issue of floaters. This problem became more pronounced, especially when the `densify_grad_threshold` was reduced from 0.0004 to 0.0002. Have you encountered similar issues? If so, how did you address them?
![image](https://github.com/user-attachments/assets/5ec3b0f1-cf07-4c6c-aeb1-44246ed71a81)
The image above is an example of NVS. I slightly shifted the view to the right （about 1m）, and noticeable floaters are still present even when rendering from the original viewpoint.

**Comment by TY424** [comment]
This might be due to the input image being relatively sparse. Could you show me the camera trajectory? If it's convenient, you can add me on WeChat. My email is [424117920@qq.com](mailto:424117920@qq.com).
