### ISSUE TITLE
How to achieve point cloud visualization？

### ISSUE THREAD

**Issue by XinyuanHu66** [TY424/AbsGS#8]
First of all, thank you for your excellent work on this project. I am currently trying to reproduce the results from your paper, and I encountered some challenges regarding the point cloud visualization. Could you kindly explain how to assign colors to the point cloud and visualize it? Any insights or guidance would be greatly appreciated.

**Comment by TY424** [comment]
Thank you for your interest in our work. I'm not quite sure what you mean by "assign colors to the point cloud and visualize it."  AbsGS can be visualized using the point cloud visualization tool provided by 3DGS.

**Comment by XinyuanHu66** [comment]
Thank you!
